%Generated by: Cdao-Store on: Thu Feb 18 18:22:27 MST 2010
/* SELECT ?tu ?node WHERE { ?node cdao:part_of <http://www.cs.nmsu.edu/~epontell/S975A2691.tre#Tree2827>. ?tu cdao:represented_by_Node ?node . } */
/* SELECT ?edge ?src ?dest WHERE { ?dest cdao:part_of <http://www.cs.nmsu.edu/~epontell/S975A2691.tre#Tree2827>. ?src cdao:part_of <http://www.cs.nmsu.edu/~epontell/S975A2691.tre#Tree2827>. ?edge cdao:has_Child_Node ?dest . ?edge cdao:has_Parent_Node ?src . } */
/* http://www.cs.nmsu.edu/~epontell/S975A2691.tre# */
/*format: generator( 'system name', 'URI', 'date'  ).
                   namespace( 'shortname', 'URI' ).
                   node( TREE_NAME, TU_NAME, NODE_NAME). 
                   edge( TREE_NAME, TREE_TYPE, EDGE_NAME, PARENT, CHILD ).*/
generator('cdao-store', 'http://www.cs.nmsu.edu/~bchisham/cdao-store', 'Thu Feb 18 18:22:27 MST 2010').
namespace( 'Tree2827', 'http://www.cs.nmsu.edu/~epontell/S975A2691.tre#' ).
namespace( 'cdao', 'http://www.evolutionaryontology.org/cdao.owl#' ).
node( 'Tree2827', 'http://www.cs.nmsu.edu/~epontell/S975A2691.tre#taxon_13', 'http://www.cs.nmsu.edu/~epontell/S975A2691.tre#Arytaina_adenocarpi' ).
node( 'Tree2827', 'http://www.cs.nmsu.edu/~epontell/S975A2691.tre#taxon_25', 'http://www.cs.nmsu.edu/~epontell/S975A2691.tre#Arytaina_devia_G' ).
node( 'Tree2827', 'http://www.cs.nmsu.edu/~epontell/S975A2691.tre#taxon_7', 'http://www.cs.nmsu.edu/~epontell/S975A2691.tre#Arytaina_devia_insularis_P' ).
node( 'Tree2827', 'http://www.cs.nmsu.edu/~epontell/S975A2691.tre#taxon_6', 'http://www.cs.nmsu.edu/~epontell/S975A2691.tre#Arytaina_devia_insularis_C' ).
edge( 'Tree2827', 'directional', 'http://www.cs.nmsu.edu/~epontell/S975A2691.tre#tree_Arytaina_adenocarpi', 'http://www.cs.nmsu.edu/~epontell/S975A2691.tre#tree', 'http://www.cs.nmsu.edu/~epontell/S975A2691.tre#Arytaina_adenocarpi').
edge( 'Tree2827', 'directional', 'http://www.cs.nmsu.edu/~epontell/S975A2691.tre#node2_Arytaina_devia_G', 'http://www.cs.nmsu.edu/~epontell/S975A2691.tre#node2', 'http://www.cs.nmsu.edu/~epontell/S975A2691.tre#Arytaina_devia_G').
edge( 'Tree2827', 'directional', 'http://www.cs.nmsu.edu/~epontell/S975A2691.tre#node2_Arytaina_devia_insularis_P', 'http://www.cs.nmsu.edu/~epontell/S975A2691.tre#node2', 'http://www.cs.nmsu.edu/~epontell/S975A2691.tre#Arytaina_devia_insularis_P').
edge( 'Tree2827', 'directional', 'http://www.cs.nmsu.edu/~epontell/S975A2691.tre#node1_node2', 'http://www.cs.nmsu.edu/~epontell/S975A2691.tre#node1', 'http://www.cs.nmsu.edu/~epontell/S975A2691.tre#node2').
edge( 'Tree2827', 'directional', 'http://www.cs.nmsu.edu/~epontell/S975A2691.tre#node1_Arytaina_devia_insularis_C', 'http://www.cs.nmsu.edu/~epontell/S975A2691.tre#node1', 'http://www.cs.nmsu.edu/~epontell/S975A2691.tre#Arytaina_devia_insularis_C').
edge( 'Tree2827', 'directional', 'http://www.cs.nmsu.edu/~epontell/S975A2691.tre#tree_node1', 'http://www.cs.nmsu.edu/~epontell/S975A2691.tre#tree', 'http://www.cs.nmsu.edu/~epontell/S975A2691.tre#node1').
