#Brandon Chisham
#3-26-08
#Build file for prototype translator.

BINDIR=bin/
LIBDIR=lib/

all:
	(cd lib && make)
	(cd src && make)
	cp src/translator bin/

clean:
	(cd lib && make clean)
	(cd src && make clean)
	rm -f bin/translator

dist:
	mkdir evo-info
	cp Makefile evo-info
	cp -R src test lib bin include doc evo-info
	tar -cz evo-info > evo-info.tar.gz
	rm -rf evo-info


