
/*
 * AddAnnotationSource.java
 *
 * Created on Apr 28, 2010, 11:38:16 PM
 */

package cdaoexplorer.forms.dialogs;

import java.net.MalformedURLException;
import java.net.URL;

/**
 *
 * @author bchisham
 */
public class AddAnnotationSource extends javax.swing.JDialog {

    /** Creates new form AddAnnotationSource */
    public AddAnnotationSource(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    /**
     * Get the symbolic name for the annotation source (e.g. dc for the dublin core).
     * @return
     */
    public String getSymbolicName(){
        return this.symbolicNameTextField.getText();
    }
    /**
     * Get the specified source url.
     * @return
     * @throws MalformedURLException
     */
    public URL getSourceURL() throws MalformedURLException{
        return new URL( this.sourceURITextField.getText());
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        symbolicNameLabel = new javax.swing.JLabel();
        sourceURILabel = new javax.swing.JLabel();
        symbolicNameTextField = new javax.swing.JTextField();
        sourceURITextField = new javax.swing.JTextField();
        importButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(AddAnnotationSource.class);
        titleLabel.setFont(resourceMap.getFont("titleLabel.font")); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText(resourceMap.getString("titleLabel.text")); // NOI18N
        titleLabel.setName("titleLabel"); // NOI18N

        symbolicNameLabel.setText(resourceMap.getString("symbolicNameLabel.text")); // NOI18N
        symbolicNameLabel.setName("symbolicNameLabel"); // NOI18N

        sourceURILabel.setText(resourceMap.getString("sourceURILabel.text")); // NOI18N
        sourceURILabel.setName("sourceURILabel"); // NOI18N

        symbolicNameTextField.setText(resourceMap.getString("symbolicNameTextField.text")); // NOI18N
        symbolicNameTextField.setName("symbolicNameTextField"); // NOI18N

        sourceURITextField.setText(resourceMap.getString("sourceURITextField.text")); // NOI18N
        sourceURITextField.setName("sourceURITextField"); // NOI18N

        importButton.setText(resourceMap.getString("importButton.text")); // NOI18N
        importButton.setName("importButton"); // NOI18N

        closeButton.setText(resourceMap.getString("closeButton.text")); // NOI18N
        closeButton.setName("closeButton"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(titleLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(sourceURILabel)
                        .add(40, 40, 40)
                        .add(sourceURITextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(symbolicNameLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(symbolicNameTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(importButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(closeButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(titleLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(symbolicNameLabel)
                    .add(symbolicNameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(sourceURILabel)
                    .add(sourceURITextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(importButton)
                    .add(closeButton))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddAnnotationSource dialog = new AddAnnotationSource(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton importButton;
    private javax.swing.JLabel sourceURILabel;
    private javax.swing.JTextField sourceURITextField;
    private javax.swing.JLabel symbolicNameLabel;
    private javax.swing.JTextField symbolicNameTextField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

}
