/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * KeyDisplay.java
 *
 * Created on Apr 16, 2010, 5:17:20 PM
 */

package matrixviewer;

import matrixviewer.model.Matrix;
import matrixviewer.view.MatrixKeyCanvas;

/**
 *
 * @author bchisham
 */
public class KeyDisplay extends javax.swing.JFrame {
    private Matrix model;

    /** Creates new form KeyDisplay */
    public KeyDisplay() {
        initComponents();
    }

    public KeyDisplay(Matrix model){
        this.model = model;
        initComponents();
        ((MatrixKeyCanvas)key_canvas).setModel(model);
        
    }

    public void setModel(Matrix model){
        this.model = model;
        ((MatrixKeyCanvas)key_canvas).setModel(model);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        key_canvas = new MatrixKeyCanvas();

        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        key_canvas.setName("key_canvas"); // NOI18N
        jScrollPane1.setViewportView(key_canvas);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KeyDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Canvas key_canvas;
    // End of variables declaration//GEN-END:variables

}
