#!/bin/bash
#Brandon Chisham
#Script to extract a prolog format tree.
#-->Params
#----->$1 database configuration string
#----->$2 tree name
#----->$3 xml base.
#----->$4 directed/undirected 
#Note do_query.py expects DBCONFIG_STRING QUERY_STRING FORMAT_STRING XML_BASE_URI

export cdao="http://www.evolutionaryontology.org/cdao.owl"
export CDAO_STORE_URI="http://www.cs.nmsu.edu/~bchisham/cdao-store"
export CDAONS="$cdao#"
export GRAPH_CONFIG="$1"
export TREE_NAME="$2"
export XMLNS="$3"
export TYPE="$4"

export NODE_QUERY=`do_tu_query_construct.sh "$XMLNS$TREE_NAME"`
export EDGE_QUERY=`do_edge_query_construct.sh "$XMLNS$TREE_NAME"`
export CTIME=`date`
echo -e "%Generated by: Cdao-Store on: $CTIME"

echo -e "/*" $NODE_QUERY "*/"
echo -e "/*" $EDGE_QUERY "*/"
echo -e "/*" $XMLNS  "*/"

echo -e "/*format: generator( 'system name', 'URI', 'date'  ).
                   namespace( 'shortname', 'URI' ).
                   node( TREE_NAME, TU_NAME, NODE_NAME). 
                   edge( TREE_NAME, TREE_TYPE, EDGE_NAME, PARENT, CHILD ).*/"
echo "generator('cdao-store', '$CDAO_STORE_URI', '$CTIME')."
echo "namespace( '$TREE_NAME', '$XMLNS' )."
echo "namespace( 'cdao', '$CDAONS' )."
do_query.py "$GRAPH_CONFIG" "$XMLNS" "$NODE_QUERY" "node( '$TREE_NAME', '%s', '%s' )." "$EDGE_QUERY" "edge( '$TREE_NAME', '$TYPE', '%s', '%s', '%s')."
