#!/bin/bash
#Brandon Chisham
#Feb. 14, 2010

#-->Params
#----->$1 database configuration string
#----->$2 tree name
#----->$3 xml base.
#----->$4 directed/undirected 
#Note do_query.py expects DBCONFIG_STRING QUERY_STRING FORMAT_STRING XML_BASE_URI

export cdao="http://www.evolutionaryontology.org/cdao.owl"



TU_QUERY=`do_tu_query_construct.sh "$2"`;
echo "%Generated by the cdao-triplestore query system on " `date`
echo "% $TU_QUERY "
echo "%format tu( tree_name, tu-id, node-name)."


do_query.py "$1" "$TU_QUERY" "tu( $2, %s, %s )." "$3"


