#Make file for compiling the paper
#Brandon Chisham
#May 14, 2010


pdf: triplestore-paper.tex abstract.tex introduction.tex methods.tex discussion.tex acknowledgements.tex references.tex
	pdflatex triplestore-paper.tex
	pdflatex triplestore-paper.tex

clean:
	rm -f *.log *.aux *.toc
