
INCLUDES= -I. -I../ -I../grammar/nexus -I../../include

CXX=g++
CXXFLAGS=-Wall -g $(INCLUDES)



all:
	make codegen.o
clean:
	echo "make clean"
codegen.o: codegen.cpp codegen.hpp
	$(CXX) $(CXXFLAGS) -c codegen.cpp
