.TH "Loggable" 3 "26 May 2006" "Version 2" "C++ Logging Facility" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Loggable \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Loggable.hpp>\fP
.PP
Inherited by HelloWorld, \fBLoggableEndLine\fP, and \fBLoggableSpace\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual std::string \fBtoString\fP () const =0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Description: Loggable specifies an interface classes may inherit to more easily integrate with the \fBLogManager\fP.
.PP
.SH "Member Function Documentation"
.PP 
.SS "virtual std::string Loggable::toString () const\fC [pure virtual]\fP"
.PP
Clients should use this interface memeber to provide the logger with a formatted message.
.PP
Implemented in \fBLoggableEndLine\fP, and \fBLoggableSpace\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for C++ Logging Facility from the source code.
