#Brandon Chisham
#Extract, configure, build, clean, etc library dependencies.

NCL=ncl
NCLV=-2.0.02


all:
	make build
unpack:
	tar -xzvf ${NCL}${NCLV}.tar.gz
	touch unpack
build: unpack
	(cd ${NCL}${NCLV} && ./configure --prefix=`pwd`/../../ && make && make install)
	touch build
clean:
	rm -rf build unpack ${NCL}${NCLV}

