.TH "CLogger" 3 "26 May 2006" "Version 2" "C++ Logging Facility" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CLogger \- 
.SH SYNOPSIS
.br
.PP
\fC#include <CLogger.hpp>\fP
.PP
Inherits \fBLogger\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCLogger\fP (FILE *&log, int nLogLevel=ERROR_MESSAGES_LR, bool closeOnExit=false)"
.br
.ti -1c
.RI "virtual void \fBlog\fP (int level=ERROR_MESSAGES_LR, const string &message='') const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Provides an interface to log to a FILE*.
.PP
.SH "Member Function Documentation"
.PP 
.SS "void CLogger::log (int level = \fCERROR_MESSAGES_LR\fP, const string & message = \fC''\fP) const\fC [virtual]\fP"
.PP
Description: Tests the log level of the message and reports the message if it has a high enough priority otherwise the message is suppressed.
.PP
Implements \fBLogger\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for C++ Logging Facility from the source code.
