.TH "LoggableSpace" 3 "26 May 2006" "Version 2" "C++ Logging Facility" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LoggableSpace \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Loggable.hpp>\fP
.PP
Inherits \fBLoggable\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual std::string \fBtoString\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
This predefined log tokent is a wrapper for the space character.
.PP
.SH "Member Function Documentation"
.PP 
.SS "virtual std::string LoggableSpace::toString () const\fC [inline, virtual]\fP"
.PP
Clients should use this interface memeber to provide the logger with a formatted message.
.PP
Implements \fBLoggable\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for C++ Logging Facility from the source code.
