#!/bin/bash
#April 12, 2010
#Script to list various characteristics of the store.

source "/home/grad6/bchisham/.bashrc"

LISTING_TYPE=$(echo "$REQUEST_URI" | grep -oE '(trees|matrices)' )
START_LIMIT=$(echo "$REQUEST_URI" | grep -oE '[0-9][0-9]*\/[1-9][0-9]*$')
START=$(echo "$START_LIMIT" | grep -oE '^[0-9][0-9]*')
LIMIT=$(echo "$START_LIMIT" | grep -oE '[1-9][0-9]*$')

XMLNS="http://www.evolutionaryontology.org/cdao.owl#"

TREE_QUERY="SELECT ?tree WHERE { ?tree rdf:type cdao:Tree. }"
MAT_QUERY="SELECT ?matrix WHERE { ?matrix rdf:type cdao:CharacterStateDataMatrix. }"

TARGET_QUERY=""

if [[ "$LISTING_TYPE" == "trees" ]]; then
   TARGET_QUERY="$TREE_QUERY"
else 
   if [[ "$LISTING_TYPE" == "matrices" ]]; then
     TARGET_QUERY="$MAT_QUERY"
   fi
fi
echo -n -e "Content-type: text/plain; charset:utf-8\n\n"
#echo "start_limit: $START_LIMIT start: $START limit: $LIMIT lines: $[ $START + $LIMIT ] "
if [[ "$START" != "" && "$LIMIT" != "" ]]; then
    cat tree_to_file.dat | head -n "$[$START + $LIMIT ]" - | tail -n "$LIMIT" - | cut -d' ' --fields=2
else
    cat tree_to_file.dat | cut -d' ' --fields=2
fi
#do_query.py "$TRIPLESTORE_CONFIG_STRING" "$XMLNS" "$TARGET_QUERY" "%s" | sort | uniq
