/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReformatPhylipForm.java
 *
 * Created on Nov 5, 2010, 8:31:23 PM
 */

package phylipalrequin;

import java.io.File;
import javax.swing.JFileChooser;
import org.jdesktop.application.Application;

/**
 *
 * @author bchisham
 */
public class ReformatPhylipForm extends javax.swing.JFrame {

    File inputLocation;
    File outputLocation;

    private void setInputLocation(){
        JFileChooser fdialog = new JFileChooser();
        fdialog.setDialogTitle( "Input Location" );
        fdialog.setDialogType( JFileChooser.OPEN_DIALOG );
        fdialog.showOpenDialog(this);

        inputLocation = fdialog.getSelectedFile();
    }

    private void setOutputLocation(){
        JFileChooser fdialog = new JFileChooser();
        fdialog.setDialogTitle( "Output Location" );
        fdialog.setDialogType( JFileChooser.SAVE_DIALOG );
        fdialog.showSaveDialog(this);

        outputLocation = fdialog.getSelectedFile();
    }



    /** Creates new form ReformatPhylipForm */
    public ReformatPhylipForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        inputLocationBtn = new javax.swing.JButton();
        outputLocationBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(phylipalrequin.PhylipAlrequinApp.class).getContext().getResourceMap(ReformatPhylipForm.class);
        setTitle(resourceMap.getString("Reformat Phylip.title")); // NOI18N
        setLocation(new java.awt.Point(100, 75));
        setName("Reformat Phylip"); // NOI18N

        title.setFont(resourceMap.getFont("title.font")); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setLabelFor(this);
        title.setText(resourceMap.getString("title.text")); // NOI18N
        title.setName("title"); // NOI18N

        inputLocationBtn.setText(resourceMap.getString("inputLocationBtn.text")); // NOI18N
        inputLocationBtn.setName("inputLocationBtn"); // NOI18N
        inputLocationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputLocationBtnActionPerformed(evt);
            }
        });

        outputLocationBtn.setText(resourceMap.getString("outputLocationBtn.text")); // NOI18N
        outputLocationBtn.setName("outputLocationBtn"); // NOI18N
        outputLocationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputLocationBtnActionPerformed(evt);
            }
        });

        exitBtn.setText(resourceMap.getString("exitBtn.text")); // NOI18N
        exitBtn.setName("exitBtn"); // NOI18N
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(title, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(inputLocationBtn)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(outputLocationBtn)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(exitBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(title)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 91, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(inputLocationBtn)
                    .add(outputLocationBtn)
                    .add(exitBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputLocationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputLocationBtnActionPerformed
        this.setInputLocation();
    }//GEN-LAST:event_inputLocationBtnActionPerformed

    private void outputLocationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputLocationBtnActionPerformed
        this.setOutputLocation();
    }//GEN-LAST:event_outputLocationBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
       this.setVisible( false );
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReformatPhylipForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton inputLocationBtn;
    private javax.swing.JButton outputLocationBtn;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

}
